# Generated by Django 5.0 on 2023-12-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(default='nothing', max_length=20),
            preserve_default=False,
        ),
    ]
