# Generated by Django 5.0 on 2023-12-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
