# Generated by Django 5.0 on 2023-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_record_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
